name: sbt test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'sbt'
    - uses: actions/setup-python@v5.4.0
      with:
        python-version: 3.10
    - name: Install python dependencies
      run: |
        python -m venv venv
        ./venv/bin/python -m pip install -r -requirements.txt
    - uses: sbt/setup-sbt@v1
    - run: sbt test
